apiVersion: v1
kind: Pod
metadata:
  name: nginx-test-remove-privs
  labels:
    app: nginx-test-remove-privs
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      allowPrivilegeEscalation: true
      privileged: false